# Generated by Django 6.0.2 on 2026-02-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='nis',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
