# Generated by Django 6.0.2 on 2026-02-07 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0002_familia_nis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('idade', models.IntegerField()),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='bolsa.familia')),
            ],
        ),
    ]
