# Generated by Django 6.0.2 on 2026-02-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0003_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
