# Generated by Django 6.0.2 on 2026-02-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0004_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='gestante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='peso',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='vacina',
            field=models.BooleanField(default=False),
        ),
    ]
