# Generated by Django 6.0.2 on 2026-02-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0005_pessoa_altura_pessoa_gestante_pessoa_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_preventivo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pccu',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='gestante',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
