# Generated by Django 6.0.2 on 2026-02-08 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0006_pessoa_data_preventivo_pessoa_pccu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas', to='bolsa.familia'),
        ),
    ]
