# Generated by Django 6.0.2 on 2026-02-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0007_alter_pessoa_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='att',
            field=models.BooleanField(null=True),
        ),
    ]
