# Generated by Django 6.0.2 on 2026-02-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0008_familia_att'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='att',
        ),
    ]
